model:
  lr: 3.0e-5
  classes: &classes
    - Atelectasis
    - Calcification of the Aorta
    - Cardiomegaly
    - Consolidation
    - Edema
    - Emphysema
    - Enlarged Cardiomediastinum
    - Fibrosis
    - Fracture
    - Hernia
    - Infiltration
    - Lung Lesion
    - Lung Opacity
    - Mass
    - No Finding
    - Nodule
    - Pleural Effusion
    - Pleural Other
    - Pleural Thickening
    - Pneumomediastinum
    - Pneumonia
    - Pneumoperitoneum
    - Pneumothorax
    - Subcutaneous Emphysema
    - Support Devices
    - Tortuous Aorta
  loss_init_args:
    class_instance_nums:
      - 67597
      - 4361
      - 76900
      - 16038
      - 38574
      - 4255
      - 30119
      - 1158
      - 11883
      - 4049
      - 10218
      - 2533
      - 79931
      - 5529
      - 41869
      - 7663
      - 69240
      - 675
      - 3369
      - 788
      - 48093
      - 543
      - 14983
      - 2453
      - 89140
      - 3499
    total_instance_num: 264849
  text_model: dmis-lab/biobert-v1.1
  timm_init_args:
    num_classes: 26
    model_name: convnext_small.fb_in22k_ft_in1k
    pretrained: true
    drop_path_rate: 0.0
  optimizer_init_args:
    weight_decay: 0.01
    betas: [0.9, 0.999]
    eps: 1.0e-8
  scheduler_init_args:
    warmup_ratio: 0.05
    warmup_start_factor: 1.0e-3
    eta_min_factor: 0.1
data:
  dataloader_init_args:
    batch_size: 4
    num_workers: 0
    pin_memory: true
    persistent_workers: true
    prefetch_factor: 2
  datamodule_cfg:
    tokenizer: dmis-lab/biobert-v1.1
    train_df_path: data/data-camchex/03_mimic_train.csv
    devel_df_path: data/data-camchex/03_mimic_development.csv
    pred_df_path: data/data-camchex/03_mimic_test.csv
    size: 512
    classes: *classes
trainer:
  max_epochs: 30
  accumulate_grad_batches: 1
  grad_clip: 1.0
  precision: 16-mixed
  compile_model: false
  log_every_n_steps: 1
  val_check_interval: null
  quick_val_every_steps: null
  quick_val_frac: 0.1
  seed: null
  accelerator: null
